### PR TITLE
Align code with best practice for passing unsafe.Pointers to system calls

### PR DESCRIPTION
**Pull request by JohnRusk**
…alls

### CODE REVIEW

**Comment by JohnRusk** [comment]
BTW, the recent forced push was just to correct a weird merge error/typo in the previous push

**Comment by JohnRusk** [comment]
And just did another forced push fix, this time fixed a really stupid typo!

**Comment by zezha-msft** [comment]
Approved. :shipit:

**Comment by JohnRusk** [comment]
Don't merge yet please. I need to check one thing.

**Comment by JohnRusk** [comment]
@jiacfan Do you want to take a look at this before merge? (I just fixed a small bug in it, so its ready to look at now).

**Review by jiacfan — APPROVED** [review]
:shipit:

**Comment by jiacfan** [comment]
@JohnRusk it looks good, thanks for optimization!

**Pull request merged**
